### ISSUE TITLE
Hello, is this a bug? I tried many times and failed

### ISSUE THREAD

**Issue by sunny-fun** [ORzazade/PUBG-heatmap-frontend#20]
Hello, is this a bug? I tried many times and failed

- [ ] [
![Snipaste_2020-08-19_19-51-42](https://user-images.githubusercontent.com/55755493/90631656-b2516e00-e255-11ea-892a-150a7d176bb6.png)
](url)

**Comment by orzazade** [comment]
Hello yes, it was a bug related to bots. Thank you for creating an issue.
