### ISSUE TITLE
The player's position on the map is flashing all the time

### ISSUE THREAD

**Issue by sunny-fun** [ORzazade/PUBG-heatmap-frontend#21]
The player's position on the map is flashing all the time

**Comment by orzazade** [comment]
I don't think it is a bug. The flashed players are bots. They are really flashing in the game.

**Comment by sunny-fun** [comment]
Please, man, this is a bug. The original author also said that it was caused by telemetry JSON. However, I don't know what's going on in my mind. I always feel that you are more fluent than the original author's when loading maps and players. It seems to be smoother with the naked eye. Have you made any changes for fluency

**Comment by orzazade** [comment]
@xbw187 I see, yes that is right, it is related to telemetry JSON. But my guess is it happens in the game too. Bots appear suddenly. What do you suggest to fix? Maybe we can ignore bots.

**Comment by orzazade** [comment]
@xbw187  Yes I made some little changes to became smoother
