### ISSUE TITLE
Hello, I see that the animation on your website is very smooth, but I'm very stuck when I download and run this project. Is this because you didn't update the latest to GitHub, or is my operation wrong

### ISSUE THREAD

**Issue by tomDogwow** [ORzazade/PUBG-heatmap-frontend#23]
Hello, I see that the animation on your website is very smooth, but I'm very stuck when I download and run this project. Is this because you didn't update the latest to GitHub, or is my operation wrong

**Comment by orzazade** [comment]
Hello, what kind of trouble do you have?

**Comment by tomDogwow** [comment]
Hello, I see the animation on your website is very smooth（ pubgheatmap.net ）When I download and run on GitHub, the replay animation is not very smooth (compared to) pubgheatmap.net This is too laggy. Is this because you haven't updated the latest version of GitHub, or am I doing something wrong @ORzazade

**Comment by orzazade** [comment]
I don't know exactly what happens, but I don't think you did something wrong.  Usually, it's normal to have a difference between debug and production mode. But if it is too bad, then probably it is related to your PC performance.  when you deploy to a server I guess it will become smooth.

**Comment by tomDogwow** [comment]
Okay, but pubgheatmap.net This website is really much smoother on the same computer,Thank you for your reply

**Comment by orzazade** [comment]
You are welcome.
